### ISSUE TITLE
Typescript errors and missing type declarations

### ISSUE THREAD

**Issue by blindfish3** [storyblok/storyblok-svelte#117]
There are multiple typescript errors being reported when I run `svelte-check` in a project that imports from `@storyblok/svelte`.  For example in @storyblok/svelte/index.ts the following are obviously problematic:

```ts
let storyblokApiInstance: StoryblokClient = null;
// ...
let componentsMap: SbSvelteComponentsMap = null;
```
There's also a hint: "Could not find a declaration file for module './StoryblokComponent.svelte'."

**Comment by josefineschaefer** [comment]
With the PR #489, the execution of svelte-check should run smoothly now :) 
Test by running `npm run check`. Let us know if the issue is still occuring?
