### ISSUE TITLE
Rendering Inline Components in Rich Text 

### ISSUE THREAD

**Issue by wilsonowilson** [storyblok/storyblok-svelte#146]
There's no information in the Readme about rendering inline components with the Svelte Components.

I assumed calling `storyblokInit` with its `components` would automatically take care of setting the component resolvers, but that doesn't seem to be the case.

How can achieve this?

**Comment by josefineschaefer** [comment]
Hi @wilsonowilson 
Thanks for your feedback :) 
Have you tried using the `renderRichText` function that comes with @storyblok/svelte and Sveltes {@html htmlstring} directive ?

Like in the example from the readme: https://github.com/storyblok/storyblok-svelte#rendering-rich-text

**Comment by wilsonowilson** [comment]
Yes, but the outputted rich text doesn't include my blocks.

**Comment by josefineschaefer** [comment]
Ok, let me investigate a little bit. I'll do my best to get back to you as soon as possible but please be patient with us :)

**Comment by josefineschaefer** [comment]
Hi @wilsonowilson 
Currently, this feature is actually not available. We are waiting for an update to storyblok/js to be able to integrate this feature. Hope to be able to give you an update here soon.

**Comment by Kainkainkain** [comment]
@wilsonowilson

I had previously solved this problem (crudely) by iterating through the richtext and essentially labelling bloks to render by loading the component switcher. 

Since every heading and paragraph is a node in this iteration, I grouped texts into "textsArray" so they could just be fed to renderRichText once.

Some of this code is about my particular project, but you can solve your problem with this

`
let finalArray = []
let textsArray = []
let blokdata = []
if (blok?.text){
    //normal
    blokdata=blok?.text?.content
}else if (blok.component == "news-article"){
    //news article
    blokdata=blok?.content?.content
} 

    if (blokdata?.length> 0 ) {
        blokdata.forEach(el => {
            // console.log(JSON.stringify(el))
            //if blok type is blok, push it to finalArray, if not push textsArray to add later in loop
            if (el.type === 'blok'){
                if (textsArray.length > 0){
                    finalArray.push({texts: [...textsArray]})
                    textsArray = []
                }
                finalArray.push({bloks: el})
            } else {
                textsArray.push(el)
            }
            
        }) 
        finalArray.push({texts: [...textsArray]})
    }

`
and then in my output div

`
 {#each finalArray as blokortext}  
    {#if !!blokortext?.bloks }  

        <span class="no-prose intextsection"> 
 

            <svelte:component
            blok={blokortext.bloks.attrs.body[0]}
            {fullslug}
            this={getComponent(blokortext.bloks.attrs.body[0].component)}/>  
        </span>

        
    {:else} 
        <span class={`${notprose ? 'not-prose':'prose'} c intextsection break-words`}
       
        >  
        
        {@html renderRichText({content:[...blokortext.texts]}) }
        </span>
    {/if}
{/each} 
`

Where getComponent is my own switching component code. 

Since adding storyblok-svelte I can't quiet get this code working properly and I'm not sure why. 
But this might help those stuck here also. 

Storyblok staff @josefineschaefer  : it would be great if the resolver could manage this, looking forward to hearing updates.

**Comment by royston-c-oa** [comment]
Below is how I got the feature working, in case it helps

``` ts
<script lang="ts">
	import { RichTextSchema, storyblokEditable, type SbBlokData } from '@storyblok/svelte';
	import { renderRichText } from '@storyblok/svelte';
	import { components } from '..';

	export let blok: RichTextProps;

	interface RichTextProps extends SbBlokData {
		content: any;
	}
	interface RichTextComponentSegmentsProps {
		component?: any;
		blok?: SbBlokData;
		html?: string;
	}

	$: contentHTML = renderRichText(blok.content, {
		schema: RichTextSchema,
		resolver: (component, blok) => {
			return `__COMPONENT__!!! ${JSON.stringify({ component, blok })} __COMPONENT__`;
		}
	});

	$: contentSegments = contentHTML.split('__COMPONENT__').map((x) => {
		if (x.startsWith('!!!')) {
			var componentJsonString = x.replace('!!!', '');
			var details = JSON.parse(componentJsonString);

			return <RichTextComponentSegmentsProps>{
				component: components[details.component],
				blok: details.blok
			};
		}
		return <RichTextComponentSegmentsProps>{
			html: x
		};
	});
</script>

<div use:storyblokEditable={blok}>
	{#each contentSegments as contentSegment}
		{#if contentSegment.html}
			{@html contentSegment.html}
		{:else}
			<svelte:component this={contentSegment.component} blok={contentSegment.blok} />
		{/if}
	{/each}
</div>

```

**Comment by wilsonowilson** [comment]
@royston-c-oa This works great. Thanks!

**Comment by enyo** [comment]
This issue should be reopened, because it is not solved. The "solution" proposed here is just a hack to get it to work.

**Comment by phenomen** [comment]
It would be nice to have a simple way of mapping Storyblok components to Svelte components so RichText would resolve those automatically.

**Comment by TomSmedley** [comment]
> Hi @wilsonowilson Currently, this feature is actually not available. We are waiting for an update to storyblok/js to be able to integrate this feature. Hope to be able to give you an update here soon.

Any update this?

**Comment by josefineschaefer** [comment]
Hi @TomSmedley, 
I might be overlooking something, but since you can now resolve rich text rendering for nested components, this should be resolved, right?
https://github.com/storyblok/storyblok-svelte#rendering-rich-text

**Comment by roberto-butti** [comment]
Hi, here I made another example of how to solve nested components in the RichText editor.
https://github.com/roberto-butti/my-storyblok-sveltekit-example/blob/main/src/routes/articles/%5Bslug%5D/%2Bpage.svelte

As you can see, I'm looping the children in the doc:
```svelte
{#each data.story.content.richtext_field.content as node, i}
    {#if node.type === "blok"}
        {#each node.attrs.body as bodyItem, idxBody}
            <StoryblokComponent
                blok="{bodyItem}"
            />
        {/each}
    {:else}
        {@html renderNode(node)}
    {/if}
{/each}
```

calling StoryblokComponent in case of "blok" or calling renderNode in other cases.
The renderNode it calls the renderRichRext with the proper structure:

```javascript
function renderNode(node) {
    return renderRichText({
        type: "doc",
        content: [node],
    });
}
```

Probably this functionality (maybe optimized and refactored) could be moved directly in the sdk and make it available for everyone.  I will take a look at this.

**Comment by Radiergummi** [comment]
I just packed @roberto-butti's solution into a `RichText.svelte` component:

```svelte
<script lang="ts">
  import { StoryblokComponent } from "@storyblok/svelte";
  import type { RichtextStoryblok } from "$storyblok/components";
  import { renderRichText } from "@storyblok/js";

  export let content: RichtextStoryblok;

  function renderNode(node: RichtextStoryblok): string {
    return renderRichText({
      type: "doc",
      content: [node],
    });
  }
</script>
<div class="rich-text">
  {#each content.content as node}
    {#if node.type === "blok"}
      {#each node.attrs.body as blok}
        <StoryblokComponent blok="{blok}" />
      {/each}
    {:else}
      {@html renderNode(node)}
    {/if}
  {/each}
</div>
```

You can just pass it a rich-text field like so:
```svelte
<RichText content={blok.your_richtext_field} />
```

I agree though, this should just be working out of the box.

**Comment by roberto-butti** [comment]
Thank you @Radiergummi, for your feedback/suggestion.

We are going to include this nice solution in the documentation (readme and ultimate tutorial).

I think we can evaluate to include this component as part of the SDK in the future.

We really appreciate your and all the community feedback about the RichText resolver 🎉

**Comment by Radiergummi** [comment]
You're welcome @roberto-butti! I'd just have one question that came up during development - should I wrap the element in a `{#key content}`, or is that only required for the top-level page Blok?
