### ISSUE TITLE
Storyblok can't load component on client side

### ISSUE THREAD

**Issue by mikedejong** [storyblok/storyblok-svelte#223]
Greetings,

Ever since we updated to the latest version of Svelte/Storyblok-svelte we've had an issue with rendering components on the client side. Server side we've had no problems, but we always get this error when we open our inspector in chrome.

We've also started a new fresh project using the steps described in [this manual](https://www.storyblok.com/tp/add-a-headless-cms-to-svelte-in-5-minutes) but the outcome was the same.

Below is the error we get in chrome. Anyone else having this issue or is it just us?

Steps to reproduce:
- Follow [the manual](https://www.storyblok.com/tp/add-a-headless-cms-to-svelte-in-5-minutes)

**Error:**
```
index.ts?v=67c36d66:60 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'default-page')
    at getComponent (index.ts?v=67c36d66:60:21)
    at instance (StoryblokComponent.svelte:8:17)
    at init (index.mjs:1892:11)
    at new StoryblokComponent (StoryblokComponent.svelte:10:79)
    at createProxiedComponent (svelte-hooks.js?v=67c36d66:341:9)
    at new ProxyComponent (proxy.js?v=67c36d66:242:7)
    at new Proxy<StoryblokComponent> (proxy.js?v=67c36d66:349:11)
    at create_if_block (+page.svelte? [sm]:3:79)
    at create_fragment (+page.svelte? [sm]:16:20)
    at init (index.mjs:1907:37)
```

**+page.js**
```
import {storyblokInit, apiPlugin, useStoryblokApi} from "@storyblok/svelte";
import Default from "../components/Default.svelte";

storyblokInit({
    accessToken: "KEY",
    use: [apiPlugin],
    components: {
        'default-page': Default
    }
});

export async function load() {
    const storyblokApi = useStoryblokApi();
    const { data } = await storyblokApi.get("cdn/stories/home", {
        version: "draft",
    });
    return {
        story: data.story
    }
}
```

**+page.svelte**
```
<script>
    import { onMount } from "svelte";
    import { useStoryblokBridge, StoryblokComponent } from "@storyblok/svelte";

    export let data;

    onMount(() => {
        useStoryblokBridge(
            data.story.id,
            (newStory) => (data.story = newStory)
        );
    });
</script>

<div>
    {#if data.story}
        <StoryblokComponent blok={data.story.content} />
    {/if}
</div>
```

**package.json**
```
{
	"name": "storietje",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch"
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"typescript": "^4.7.4",
		"vite": "^3.1.0",
		"vite-plugin-mkcert": "^1.9.0"
	},
	"type": "module",
	"dependencies": {
		"@storyblok/svelte": "^2.3.2"
	}
}
```

**Comment by wilsonowilson** [comment]
Hey! I'm facing the same issue for my project.
SSR works fine but CSR fails completely for no reason.

**Comment by sebasvdonk** [comment]
I'm having the same issue as well, ever since the new routing update. This has held us back from updating to the latest version, because SSR and SEO is a pretty big deal for us.

Just like @wilsonowilson mentioned, SSR works fine but the CSR fails. It seems like the SDK loads in all the components and successfully executes the SSR call, but once the CSR call comes in it no longer knows which components have been loaded in.

**Comment by fairEnough83** [comment]
same issue for us - please help

**Comment by loghomefinishing** [comment]
can't get anything to work with Svelte + StoryBlok

**Comment by sebasvdonk** [comment]
> Any updates on this? This issue is completely blocking my migration to the latest Sveltekit.

I think the Storyblok team hasn't come around to update this yet. However I think I located the issue. It seems the latest SvelteKit version no longer waits on individual components to render. So for instance, the page could be done loading before the layout is, or a block inside the page could be done before a page is rendered. 

This means that Storyblok tries to use components inside the Storyblok component directive, that haven't been initialised in the StoryblokInit function yet, hence the issue.

**Comment by alexjoverm** [comment]
Hey everyone! Sorry for the waiting, we're actually investigating the issue and determining if we can do something from our SDK or is more in userland, as the SDK is working with Svelte and used to work with SvelteKit until a certain point.

We'll keep you in the loop

**Comment by enyo** [comment]
I just ran in the same issue (I think). SSR is working fine (I can see the page) but after hydration I get:

```
SyntaxError: ambiguous indirect export: default
```

This seems to be a different error message though? Is this related?

**Comment by enyo** [comment]
> > Any updates on this? This issue is completely blocking my migration to the latest Sveltekit.
> 
> I think the Storyblok team hasn't come around to update this yet. However I think I located the issue. It seems the latest SvelteKit version no longer waits on individual components to render. So for instance, the page could be done loading before the layout is, or a block inside the page could be done before a page is rendered.
> 
> This means that Storyblok tries to use components inside the Storyblok component directive, that haven't been initialised in the StoryblokInit function yet, hence the issue.

Do you have a solution to this to get it to work?

**Comment by enyo** [comment]
Ok, so I found the solution to the general problem described here.

As @sebasvdonk pointed out, the issue is that the `load` functions are not invoked in the right order, which is by design. To make sure that the `+page.js` load function is invoked _after_ the `+layout.js` function (which initialises storyblok).

So the way it works without an issue for me is to put the `storyblokInit` function in the `load()` function of `+layout.js` and then wait for that load function to complete in `+page.js` like this:

```js
export const load = async ({ params, parent }) => {
  // Waiting for storyblok to be initialised.
  await parent()
  // ...
}
```

* * *

The other issue I was running in was fixed by adding this to my `svelte.config.js`:

```js
  kit: {
    // ...
    alias: {
      '@storyblok/svelte': './node_modules/@storyblok/svelte',
    },
  },
```

I'm not sure why this is needed, but it fixed it for me.

* * *

Finally, I had some type issues and other weird behaviour with this lib. This was due to `@storyblok/js` not being a `peerDependency` of `storyblok/storyblok-svelte`. Simply adding `@storyblok/js` as a dev dependency solved this for me.

**Comment by roberto-butti** [comment]
Thank you @enyo , I pushed some days ago a commit for reorganizing the usage of load in layout and page (especially for the initialization of all stuff).
If you want you can provide me with some feedback on 
https://github.com/storyblok/storyblok-svelte/blob/main/playground-sveltekit/src/routes/%2Blayout.js
and
https://github.com/storyblok/storyblok-svelte/blob/main/playground-sveltekit/src/routes/%2Bpage.js

In this way, we have a better management for initializing and retrieving stuff via API according with the latest changes of SvelteKit.

I was, also, trying to solve an issue with the Bridge. For this, I will try to follow your suggestion on the alias and the peerdep.
I will let you know. Thank you for sharing this!

**Comment by enyo** [comment]
@roberto-butti oh yeah, that looks like the cleanest solution actually! Nice job.

**Comment by roberto-butti** [comment]
@enyo  and i can confirm that the alias solves the issue on the bridge.
I pushed a branch for the "Ultimate tutorial" https://github.com/storyblok/sveltekit-ultimate-tutorial-series/tree/update/part-1-sveltekit-ut

We are testing it and we will update the documentation. I hope that there will be no Breaking changes on the SvelteKit side. The SvelteKit is in Release Candidate, The sveltekit team is doing a great job, i love all the newest implementations and refactors!

**Comment by mikedejong** [comment]
Thanks for the solution guys, we've just created a PR with the latest version of Vite, SvelteKit en Storyblok and everything is working fine just like before! 🎉
