### ISSUE TITLE
Providing a custom schema doesn't work

### ISSUE THREAD

**Issue by enyo** [storyblok/storyblok-svelte#292]
When I edit the `RichTextSchema` from `@storyblok/svelte` directly it works, but if I use this code (which was initially in the README):

```ts
const MyRichTextSchema = clone(RichTextSchema)
MyRichTextSchema.marks.link = (node: ISbNode) => {
  const result = RichTextSchema.marks.link(node)
  console.log('My implementation')
  return result
}

storyblokInit({
    accessToken: storyblokAccessToken,
    use: [apiPlugin],
    bridge: useBridge,
    richText: {
      schema: MyRichTextSchema
  }
});
```

the function is never run.

**Comment by sebasvdonk** [comment]
Have you tried using the apiOptions property?

`	storyblokInit({
		accessToken: storyblokAccessToken,
		use: [apiPlugin],
		bridge: useBridge,
		apiOptions: {
			richText: {
				schema: MyRichTextSchema,
			},
		},
	});
`

**Comment by enyo** [comment]
Thanks @sebasvdonk that worked
