### ISSUE TITLE
[GUIDE] Fix for StoryblokComponent and RichText

### ISSUE THREAD

**Issue by TomSmedley** [storyblok/storyblok-svelte#439]
Hey everyone,

As many you may know the DX for Storyblok with Svelte doesn't quite live up to it's React and Vue counterparts. However, Svelte is very powerful and so is Storyblok, so correcting these are fairly simple. You may find that declaring components in `+layout.js/ts` isn't working for RichText or you're getting errors when using StoryblokComponent. Hopefully we will see these fixed soon, but in the mean time, here are some work arounds:

First lets start with StoryblokComponent, this can be fixed by creating a `StoryblokComponent.svelte` and using it like the following:
```js
<script lang="ts">
	import Buttons from '$lib/blocks/Buttons.svelte';
	import CallToAction from '$lib/blocks/CallToAction.svelte';
	import Container from '$lib/blocks/Container.svelte';
	import Content from '$lib/blocks/Content.svelte';
	import HorizontalRule from '$lib/blocks/HorizontalRule.svelte';
	import LargeImage from '$lib/blocks/LargeImage.svelte';
	import LogoAnimationBlock from '$lib/blocks/LogoAnimationBlock.svelte';
	import Pullout from '$lib/blocks/Pullout.svelte';
	import RichText from '$lib/blocks/RichText.svelte';
	import Ticker from '$lib/blocks/Ticker.svelte';
	import Title from '$lib/blocks/Title.svelte';

	export let blok: any;

	const components: any = {
		buttons: Buttons,
		callToAction: CallToAction,
		container: Container,
		content: Content,
		horizontalRule: HorizontalRule,
		largeImage: LargeImage,
		logoAnimation: LogoAnimationBlock,
		pullout: Pullout,
		richText: RichText,
		ticker: Ticker,
		title: Title
	};
</script>

<svelte:component this={components[blok.component]} {blok} />
```

Then on your RichText blok you can do the following:
```js
<script lang="ts">
	import { renderRichText } from '@storyblok/svelte';

	import StoryblokComponent from '$lib/StoryblokComponent.svelte';

	$: render = renderRichText(blok.content, {
		resolver: (_, blok) => `__BLOK__!!!${JSON.stringify(blok)}__BLOK__`
	});

	$: segments = render.split('__BLOK__').map((html: string) => {
		if (html.startsWith('!!!')) {
			const parseComponent = JSON.parse(html.replace('!!!', ''));
			return { blok: parseComponent };
		}
		return { html };
	});

	export let blok: any;
</script>

{#each segments as segment}
	{#if segment.html}
		{@html segment.html}
	{:else}
		<StoryblokComponent blok={segment.blok} />
	{/if}
{/each}
```
Credit: [royston-c-oa](https://github.com/royston-c-oa)

Hope you find this helpful until the package catches up.

**Comment by TomSmedley** [comment]
Hi @jenseo 

Are you using `prerender = true`? I've found it best to avoid it as you have to deploy again to see the update. There are ways around it such as checking your ENV, but depending on your application the 1,000,000 API calls should be fine.

**Comment by jenseo** [comment]
> Hi @jenseo 
> 
> 
> 
> Are you using `prerender = true`? I've found it best to avoid it as you have to deploy again to see the update. There are ways around it such as checking your ENV, but depending on your application the 1,000,000 API calls should be fine.

Cheers Tom, we do indeed prerender, will try switching to SSR in the preview environments and see if that does the trick! 🙏

**Comment by jenseo** [comment]
Thanks @TomSmedley , that did the trick!

**Comment by matfantinel** [comment]
Any idea how to do this trick when using a custom resolver? I am creating a RichtextResolver to be able to use a custom schema, but can't figure out where/how to add a similar logic to this.

```typescript
const resolver = new RichtextResolver(myCustomSchema);
const renderedContent = renderRichText(blok.content, undefined, resolver);
```
